version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - bodyclose
    - durationcheck
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive

  settings:
    revive:
      rules:
        - name: exported
