version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
    - durationcheck
    - predeclared
    - prealloc

  settings:
    govet:
      enable:
        - nilfunc
        - printf
        - structtag
        - unmarshal
        - unreachable
        - unusedresult
        - lostcancel
        - sortslice
        - stdmethods  
        - unusedwrite
    revive:
      rules:
        - name: atomic
        - name: exported
        - name: empty-block
        - name: confusing-results
        - name: unused-parameter
        - name: unnecessary-stmt
        - name: call-to-gc
        - name: unexported-naming
        - name: useless-break
        - name: optimize-operands-order

