package oracle

// Hint tokens used across oracles.
const (
	HintHashJoin         = "HASH_JOIN"
	HintNoHashJoin       = "NO_HASH_JOIN"
	HintMergeJoin        = "MERGE_JOIN"
	HintInlJoin          = "INL_JOIN"
	HintInlHashJoin      = "INL_HASH_JOIN"
	HintHashJoinBuild    = "HASH_JOIN_BUILD"
	HintHashJoinProbe    = "HASH_JOIN_PROBE"
	HintLeading          = "LEADING"
	HintStraightJoin     = "STRAIGHT_JOIN"
	HintSemiJoinRewrite  = "SEMI_JOIN_REWRITE"
	HintNoDecorrelate    = "NO_DECORRELATE"
	HintHashAgg          = "HASH_AGG"
	HintStreamAgg        = "STREAM_AGG"
	HintAggToCop         = "AGG_TO_COP"
	HintSetVar           = "SET_VAR"
	HintLeadingFmt       = "LEADING(%s)"
	HintUseIndexFmt      = "USE_INDEX(%s)"
	HintUseIndexMergeFmt = "USE_INDEX_MERGE(%s)"
)

// SET_VAR hint strings used by DQP.
const (
	SetVarEnableHashJoinOn               = "SET_VAR(tidb_opt_enable_hash_join=ON)"
	SetVarEnableHashJoinOff              = "SET_VAR(tidb_opt_enable_hash_join=OFF)"
	SetVarEnableNonEvalScalarSubqueryOn  = "SET_VAR(tidb_opt_enable_non_eval_scalar_subquery=ON)"
	SetVarEnableNonEvalScalarSubqueryOff = "SET_VAR(tidb_opt_enable_non_eval_scalar_subquery=OFF)"
	SetVarEnableSemiJoinRewriteOn        = "SET_VAR(tidb_opt_enable_semi_join_rewrite=ON)"
	SetVarEnableSemiJoinRewriteOff       = "SET_VAR(tidb_opt_enable_semi_join_rewrite=OFF)"
	SetVarEnableNoDecorrelateOn          = "SET_VAR(tidb_opt_enable_no_decorrelate_in_select=ON)"
	SetVarEnableNoDecorrelateOff         = "SET_VAR(tidb_opt_enable_no_decorrelate_in_select=OFF)"
	SetVarEnableOuterJoinReorderOn       = "SET_VAR(tidb_enable_outer_join_reorder=ON)"
	SetVarEnableOuterJoinReorderOff      = "SET_VAR(tidb_enable_outer_join_reorder=OFF)"
	SetVarEnableInlJoinInnerMultiOn      = "SET_VAR(tidb_enable_inl_join_inner_multi_pattern=ON)"
	SetVarEnableInlJoinInnerMultiOff     = "SET_VAR(tidb_enable_inl_join_inner_multi_pattern=OFF)"
	SetVarAllowMPPOn                     = "SET_VAR(tidb_allow_mpp=ON)"
	SetVarAllowMPPOff                    = "SET_VAR(tidb_allow_mpp=OFF)"
	SetVarEnforceMPPOn                   = "SET_VAR(tidb_enforce_mpp=ON)"
	SetVarEnforceMPPOff                  = "SET_VAR(tidb_enforce_mpp=OFF)"
	SetVarPartialOrderedTopNCost         = "SET_VAR(tidb_opt_partial_ordered_index_for_topn='COST')"
	SetVarPartialOrderedTopNDisable      = "SET_VAR(tidb_opt_partial_ordered_index_for_topn='DISABLE')"
	SetVarEnableTojaOn                   = "SET_VAR(tidb_opt_use_toja=ON)"
	SetVarEnableTojaOff                  = "SET_VAR(tidb_opt_use_toja=OFF)"
	SetVarForceInlineCTEOn               = "SET_VAR(tidb_opt_force_inline_cte=ON)"
	SetVarForceInlineCTEOff              = "SET_VAR(tidb_opt_force_inline_cte=OFF)"
	SetVarPartitionPruneDynamic          = "SET_VAR(tidb_partition_prune_mode='dynamic')"
	SetVarPartitionPruneStatic           = "SET_VAR(tidb_partition_prune_mode='static')"
	SetVarFixControl33031On              = "SET_VAR(tidb_opt_fix_control='33031:ON')"
	SetVarFixControl33031Off             = "SET_VAR(tidb_opt_fix_control='33031:OFF')"
	SetVarFixControl44830On              = "SET_VAR(tidb_opt_fix_control='44830:ON')"
	SetVarFixControl44830Off             = "SET_VAR(tidb_opt_fix_control='44830:OFF')"
	SetVarFixControl44855On              = "SET_VAR(tidb_opt_fix_control='44855:ON')"
	SetVarFixControl44855Off             = "SET_VAR(tidb_opt_fix_control='44855:OFF')"
	SetVarFixControl45132Zero            = "SET_VAR(tidb_opt_fix_control='45132:0')"
	SetVarJoinReorderThresholdFmt        = "SET_VAR(tidb_opt_join_reorder_threshold=%d)"
)
